### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by devlancer412** [AluVM/rust-aluvm#109]
![image](https://github.com/AluVM/rust-aluvm/assets/101313445/e0395469-78cb-4353-b8a8-f16bb69ba6e0)

**Comment by dr-orlovsky** [comment]
v0.10.6 is outdated, use the `v0.11.0-beta.4` or the master tip

**Comment by devlancer412** [comment]
I'm getting this error while using rgb-contracts. What's the updated version of rgb-contracts that uses that version

**Comment by dr-orlovsky** [comment]
@devlancer412 it is the master in https://github.com/RGB-WG/rgb. The v0.10 of RGB is outdated and assets issued under it won't be valid in the future.

If you will not be able to compile the master than you can file the issue in that repository
