### ISSUE TITLE
Do a test coverage

### ISSUE THREAD

**Issue by dr-orlovsky** [AluVM/rust-aluvm#20]

**Comment by josediegorobles** [comment]
Hi, this issue is about start writing test? There are some guidlines for this?

**Comment by dr-orlovsky** [comment]
Yes, the issue is about starting doing at least some tests (any are better than none) and there is no guideline other than official rust testing guidelines https://doc.rust-lang.org/book/ch11-00-testing.html

**Comment by josediegorobles** [comment]
Hi, I'm starting with numbers.rs because I can see easier what to test.

I'm started with this:

fn asserting_layouts_kinds() {
        let signed_integer_layout = Layout::Integer(IntLayout::signed(33));
        assert!(signed_integer_layout.is_signed_int());
        assert!(!signed_integer_layout.is_unsigned_int());
        assert!(!signed_integer_layout.is_float());
                
        let unsigned_integer_layout = Layout::Integer(IntLayout::unsigned(33));
        assert!(unsigned_integer_layout.is_unsigned_int());
        assert!(!unsigned_integer_layout.is_signed_int());
        assert!(!unsigned_integer_layout.is_float());
    }

It's reasonable to test it? I test all kinds of layout and checks (isfloat, is_signed_integer) in one test and make another test?

Thanks.
