### ISSUE TITLE
`sub`/`dec` instruction fails

### ISSUE THREAD

**Issue by 6293** [AluVM/rust-aluvm#36]
@dr-orlovsky 

```rust
let code = aluasm! {
        put 4,a16[8];
        sub 9,a16[8];
        ret;
    };
```

this would fail because

https://github.com/internet2-org/rust-aluvm/blob/d67e2f558cf7c300dbd516897e81e5b13a82b609/src/isa/exec.rs#L471

here, `val` is stored as unsigned Number while `Number::from(-step.as_i16())` produces signed Number, causing

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Integer(IntLayout { signed: false, bytes: 2 })`,
 right: `Integer(IntLayout { signed: true, bytes: 2 })`: subtracting numbers with different layout', src/data/arithm.rs:143:9
```
 We can fix this to something like below?

```rust
if step.as_i16() < 0 {
  val.int_sub(Number::from(<convert -step to u16>), IntFlags {
     signed: false,
     wrap: true,
  })
}
```

**Comment by z8674558** [comment]
will work on making `examples/asm.rs` work, after #34 and #35 are merged

**Comment by dr-orlovsky** [comment]
@6293 I assume this is fixed?

**Comment by 6293** [comment]
It looks it's not, the test will not pass. I'll check

**Comment by 6293** [comment]
@dr-orlovsky do you have a clarification for the "overflow" [here](https://github.com/AluVM/rust-aluvm/blob/9283433ce8c17c56781e98161f1c0592f213bbf8/src/isa/instr.rs#L472)? Is it an overflow in unsigned or signed?

e.g. [`a16` register stores its values as `u16`](https://github.com/AluVM/rust-aluvm/blob/fcfc91227468f646585887104bbf0c469e14bfae/src/reg/core_regs.rs#L48). In other arithmetic operations like `Add`, they have `IntFlags` to determine if an operation should be performed as signed or not. `Stp` does not have such flags, and I assume `Stp` should perform unsigned addition/subtraction because [your original code](https://github.com/AluVM/rust-aluvm/blob/d67e2f558cf7c300dbd516897e81e5b13a82b609/src/isa/exec.rs#L476) says so. On this assumption, 

```
put 4,a16[8];
sub 9,a16[8];
ret;
```
this code in question should set `st0` to `false` instead of setting -5 to `a16[8]`.

**Comment by 6293** [comment]
https://github.com/AluVM/aluasm/blob/5de7ed3a5c77a29f2d4925b2a4eb719cc50053df/tests/asm.rs#L203-L208

there are already some tests based on possibly wrong assumption

**Comment by dr-orlovsky** [comment]
Yes, `stp` should assume unsigned numbers. So the implementation is correct and the doc comment should be extended with that information.

Not sure I understood the second part which for me seems unrelated to `stp` question... Can you pls elaborate a bit more?

**Comment by 6293** [comment]
> Not sure I understood the second part which for me seems unrelated to stp question... Can you pls elaborate a bit more?

`sub` mnemonic is internally deserialized as `ArithmeticOp::Stp` if second param is a number literal. That's why I was concerned about `sub`
https://github.com/AluVM/aluasm/blob/1df061847a220e6afb0ba3bf0190f717ddf4eb2b/src/pipelines/compiler.rs#L863
