### ISSUE TITLE
Implement tappered float type

### ISSUE THREAD

**Issue by dr-orlovsky** [AluVM/rust-aluvm#5]
- [ ] Core type implementation
- [ ] NaN detection:
https://github.com/internet2-org/rust-aluvm/blob/14c48e90e8972543962d51b52bb8900c173548aa/src/reg/number.rs#L677-L677
- [ ] addition
- [ ] subtraction
- [ ] multiplication
- [ ] division

**Comment by 6293** [comment]
@dr-orlovsky [Posit](https://posithub.org/docs/Posits4.pdf) looks nice among various tapered float standards. I will try to implement it on amplify repo

**Comment by dr-orlovsky** [comment]
With v0.12, this should be done as an independent ISA extension
