### ISSUE TITLE
Implement BLAKE3 opcodes

### ISSUE THREAD

**Issue by dr-orlovsky** [AluVM/rust-aluvm#68]

**Comment by dr-orlovsky** [comment]
It must be checked not to break WASM compatibility: https://github.com/strict-types/strict-types/pull/10

**Comment by crisdut** [comment]
Hello @dr-orlovsky, how are you?

I want to learn about AluVM, and there is nothing better than solving a problem as it is.

I implemented Blake3 in AluVM, but how do I test it?

I didn't find automated tests for hash functions, and I was unsure how to do the tests.

Thanks

**Comment by dr-orlovsky** [comment]
Thank you for your interest! The only way to test it is to find test vectors for BLAKE3 and write unit tests. Or, in more simple way, you can hash with Blake3 API directly - and compare result with what you receive from AluVM script executing that op code

**Comment by crisdut** [comment]
> Thank you for your interest! The only way to test it is to find test vectors for BLAKE3 and write unit tests. Or, in more simple way, you can hash with Blake3 API directly - and compare result with what you receive from AluVM script executing that op code

Great!

Thank you.

**Comment by fengjian** [comment]
Hi
If you want to implement BLAKE3 opcode, I recommend using [](https://github.com/BLAKE3-team/BLAKE3). The opcode is defined as follows:

``` 
// ### Hashing (BPDIGEST)

pub const INSTR_RIPEMD: u8 = 0b10_000_000;
pub const INSTR_SHA256: u8 = 0b10_000_001;
pub const INSTR_SHA512: u8 = 0b10_000_010;
pub const INSTR_BLAKE3: u8 = 0b10_000_100;
```

**Comment by dr-orlovsky** [comment]
Should be done as an independed ISA extension
