### ISSUE TITLE
do you think we should fix the alignment of members on `Instr` enum variants to match mnemonic on 1.0.0 release?

### ISSUE THREAD

**Issue by 6293** [AluVM/rust-aluvm#79]
https://github.com/AluVM/rust-aluvm/pull/77#pullrequestreview-1479062131

**Comment by dr-orlovsky** [comment]
Yes. But there is more: alignment of bytecode serialization. It will be nice to have it the same, bit this is much more breaking than just API break.

**Comment by dr-orlovsky** [comment]
Superseded by & closed due to https://github.com/AluVM/rust-aluvm/issues/83
