### ISSUE TITLE
Cursor doesn't read accross bytes

### ISSUE THREAD

**Issue by 6293** [AluVM/rust-aluvm#86]
https://github.com/AluVM/rust-aluvm/blob/eb4fcc41c5f01bbba1d9b6494227f0d9096429c0/src/isa/bytecode.rs#L950-L955

Here, `reg` spans across 2 bytes (last bit of first byte to third bit of second byte). `write_u4`, however, does not handle such cases https://github.com/AluVM/rust-aluvm/blob/866f9c8abd409578b8c34e047f581919dd800517/src/library/cursor.rs#L129

**Comment by dr-orlovsky** [comment]
Very good point. I think this may be also the case for other serialization
