### ISSUE TITLE
`Number` often uses `to_u1024_bytes` for bitwise/arithmetic operations, but u1024 has 128bytes while `Number` is up to 1024bytes

### ISSUE THREAD

**Issue by 6293** [AluVM/rust-aluvm#88]
https://github.com/AluVM/rust-aluvm/blob/2bde05b47e10fc0a06eb12c868a14dbeff1551ec/src/data/bitwise.rs#L50-L57

https://github.com/AluVM/rust-aluvm/blob/97bd8e7c3e95093a9bf5960b82775f39df3ebeed/src/data/arithm.rs#L128-L133

**Comment by dr-orlovsky** [comment]
It is true, but it is just a sideffect. The only solution to this is to have a different Number types for A and R registers. There is no point in SHL/SHR and other arithmetic operations for R register since they are used to represent hashes/curve points and can't be operated with normal arithmetics.

**Comment by 6293** [comment]
> There is no point in SHL/SHR and other arithmetic operations for R register

Unlike bitwise operations like SHL/SHR, Arithmetic operation does not exist for R register. Instead of introducing another `Number` type for R-reg, can we stop using `Number` on bitwise operations?

**Comment by 6293** [comment]
because it is relatively easier to perform bitwise operations on byte array, than arithmetic operations

**Comment by dr-orlovsky** [comment]
I think this is a very good idea!

**Comment by dr-orlovsky** [comment]
The change is quite complex: it requires changing multiple APIs which abstract a specific register type and allow to operate with any A, R or F register providing `Number`/`MaybeNumber`.

The change is also an API-breaking

**Comment by 6293** [comment]
We we need to do is to change [CoreRegs::get](https://github.com/AluVM/rust-aluvm/blob/0e5ffc4bf63559d73a8530ebb4cef19ff5581b76/src/reg/core_regs.rs#L210) so that it accepts `impl Into<RegAF>` instead of `impl Into<RegAFR>`. When one wants to get R-reg value, they should use `CoreRegs::get_r` instead

**Comment by dr-orlovsky** [comment]
Agree, that is the best way forward.

**Comment by dr-orlovsky** [comment]
It's ok to have API breaking changes - the bytecode breakes (or business logic in instruction execution) is much much worse.

I think your proposal is a good solution.

**Comment by 6293** [comment]
Hi, hasn't been active for a while. I am facing a challenge regarding with the solution above. Taking `MoveOp::MovR` for example:

```rust
MoveOp::MovR(reg, idx1, idx2) => {
    regs.get_r_mut(*reg, idx2).copy_from_slice(regs.get_r(*reg, idx1));
}
```

This will not compile because it borrows `regs` as immutable while also borrowing as mutable. We cannot indicate on a method signature that only a subset of the struct is borrowed. One way to solve this problem is that just expose [registers](https://github.com/AluVM/rust-aluvm/blob/0e5ffc4bf63559d73a8530ebb4cef19ff5581b76/src/reg/core_regs.rs#L69) across crate. Alternatively we can have [similar getter/setter as RegAF registers](https://github.com/AluVM/rust-aluvm/blob/0e5ffc4bf63559d73a8530ebb4cef19ff5581b76/src/reg/core_regs.rs#L210), which creates a copy of register value instead of returning reference. With this approach, however, I am afraid that copying of large array occurs too often.

**Comment by dr-orlovsky** [comment]
I think we just need to clone the result of `regs.get_r` here - that will be much simplier. Not perfect, but it will make refactoring reasonably-sized.

**Comment by 6293** [comment]
A heap allocation is inevitable when cloning a slice. I thought we should ensure that a program would run without any memory allocation except at VM startup time, are we ok with that?

**Comment by dr-orlovsky** [comment]
The point was to avoid large memory allocations which may affect low-end hardware (like 64kB etc).

Even now AluVM does a lot of allocations of a smaller size.

**Comment by dr-orlovsky** [comment]
I mean it would be great to avoid any allocations runtime, but I think this is the larger goal than the scope of this issue and it will require more refactoring, so should be left for the future.

**Comment by dr-orlovsky** [comment]
Fulfilled with v0.12
