### ISSUE TITLE
Assignment to large R-reg panics

### ISSUE THREAD

**Issue by 6293** [AluVM/rust-aluvm#89]
Assignment to large R-regs like
```rust
regs.r2048[0] = Some([0u8; 256])
``` 

panics with uncanny message `thread panicked while panicking. aborting.`. This is a same bug as https://github.com/AluVM/rust-aluvm/issues/40, 

```rust
pub(crate) r1024: Box<[Option<[u8; 128]>; 32]>,
pub(crate) r2048: Box<[Option<[u8; 256]>; 32]>,
pub(crate) r4096: Box<[Option<[u8; 512]>; 32]>,
pub(crate) r8192: Box<[Option<[u8; 1024]>; 32]>,
```
too many things are on stack. R-regs should be something like

```rust
pub(crate) r1024: Confined<Vec<Option<[u8; 128]>>, 32, 32>,
pub(crate) r2048: Confined<Vec<Option<[u8; 256]>>, 32, 32>,
pub(crate) r4096: Confined<Vec<Option<[u8; 512]>>, 32, 32>,
pub(crate) r8192: Confined<Vec<Option<[u8; 1024]>>, 32, 32>,
```

**Comment by dr-orlovsky** [comment]
1. We need to allocate all registers at startup time - to ensure that runtime can run any program without memory allocation exceptions even on a low-end hardware
2. My assumption was that `Box` provides (a) heap allocation (b) at the initialization time. Now I understand that it is not the case.
3. Thus `Vec` also doesn't seem to be a solution.

Do you aware of any way we can allocate data in heap in rust during struct initialization?

**Comment by 6293** [comment]
> My assumption was that Box provides (a) heap allocation (b) at the initialization time. Now I understand that it is not the case.

This behavior happens only on static-size array, LLVM wrongly placing  it on stack first, then copying it to heap. We need `box` syntax to resolve this.

> Thus Vec also doesn't seem to be a solution.

With `Vec::with_capacity` api, heap allocation occurs only once at the initialization time ,because the length is known. We can initialize `r1024` with `Confined::from_inner(Vec::with_capacity(32))`
